name: CI - Compile

on:
  push:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build Yocto Rootfs
      run:  |
        source poky/oe-init-build-env .
        bitbake stephendpmurphy-image
